config/routes.rb
Rails.application.routes.draw do
  match 'monit(/*other)', via: :all, to: 'monit#index'

  get 'status/dj'

  get 'status/resque'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  mount Resque::Server.new, :at => "/resque"

  resources :articles

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/monit_web.rb
class MonitWeb < Rack::Proxy

  def rewrite_env(env)
    env["HTTP_HOST"] = "localhost:2812"
    # env["REQUEST_PATH"] = '/_runtime'
    env["PATH_INFO"] = "/#{env['action_dispatch.request.parameters']['other']}"
    puts env["PATH_INFO"]
    # env["REQUEST_URI"] = '/_runtime'
    # env.each {|key, value| puts "#{key}=#{value}"}
    # puts env.inspect

    env
  end

  def rewrite_response(triplet)
    status, headers, body = triplet

    # headers["X-Foo"] = "Bar"

    triplet
  end

end

app/models/status.rb
class Status < ActiveRecord::Base
  @queue = :status

  def self.new_delayed_job
    status = Status.new
    status.state = "testing"
    status.desc = "delayed_job status"
    status.save!
    if Rails.env.development?
      status.run_delayed_job
      # status.delay.run_delayed_job
    else
      status.delay.run_delayed_job
    end
    status.wait
    status
  end

  def result
    if state == 'complete'
      "-OK-"
    else
      "ERROR"
    end
  end

  def run_delayed_job
    self.state = 'complete'
    self.save!
  end

  def wait
    start = Time.zone.now
    Status.uncached do
      loop do
        reload
        break if state == 'complete' || Time.zone.now - start > 10.seconds
        # break if state == 'complete' || Time.zone.now - start > 3.seconds
        sleep(1.0/10.0)
      end
    end
  end

  def self.new_resque_job
    status = Status.new
    status.state = "testing"
    status.desc = "resque status"
    status.save!
    if Rails.env.development?
      # Status.perform(status.id)
      Resque.enqueue(Status, status.id) # start a worker with `INTERVAL=0.1 QUEUE=* rake environment resque:work`
    else
      Resque.enqueue(Status, status.id)
    end
    status.wait
    status
  end

  def self.perform(status_id)
    status = Status.find(status_id)
    status.state = 'complete'
    status.save!
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/monit_controller.rb
class MonitController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @result = MonitWeb.new.call(request.env)
    # puts request.env.inspect
    # render :status => 200, :content_type => @result[1]["content-type"], :layout => false, :text => @result[2]
    text = @result[2].to_s
    # text.gsub!(/href='/, "/href='monit/")
    render :status => 200, :layout => false, :text => text
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def dj
    @status = Status.new_delayed_job
  end

  def resque
    @status = Status.new_resque_job
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/monit_helper.rb
module MonitHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

<hr>
<h2>Delayed Job</h2>

<div><%= link_to 'Delayed Job Test', status_dj_path %></div>
<div><%= link_to 'Delayed Job Status', '/delayed_job' %></div>

<h2>Resque</h2>

<div><%= link_to 'Resque Test', status_resque_path %></div>
<div><%= link_to 'Resque Status', '/resque' %></div>

<h2>Monit</h2>

<div><%= link_to 'Monit Web', '/monit/' %></div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PvcglueDevBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/monit/index.html.erb
<h1>Monit#index</h1>
<p>Find me in app/views/monit/index.html.erb</p>

app/views/status/dj.html.erb
<h1>Delayed Job System Status</h1>
<p><%= "#{@status.result}" %></p>

app/views/status/resque.html.erb
<h1>Resque System Status</h1>
<p><%= "#{@status.result}" %></p>